common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name='common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup')
]

main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.blog, name='blog'),
    path('<int:pk>/', views.posting, name="posting"),
    path('new_post/', views.new_post),
    path('<int:pk>/remove/', views.remove_post),
    path('<int:pk>/edit/',views.edit_post),
]

web_study/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('main.urls')),
    path('', views.index, name='index'),
    path('common/', include('common.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    postname = models.CharField(max_length = 50)
    mainphoto = models.ImageField(blank=True, null=True)
    contents = models.TextField()
    # model.DateTimeField('date published') 도 가능

    def __str__(self):
        return self.postname

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model=User
        fields = ("username", "password1", "password2", "email")

common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from common.forms import UserForm

# Create your views here.

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username = username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm
    return render(request, 'common/signup.html', {'form':form})

main/views.py
from django.shortcuts import render, redirect
from .models import Post

# Create your views here.
def index(request):
    return render(request, 'index.html')

def blog(request):
    postlist = Post.objects.all()
    return render(request, 'main/blog.html', {'postlist': postlist})

def posting(request, pk):
    post = Post.objects.get(pk = pk)
    return render(request, 'main/posting.html', {'post':post})

def new_post(request):
    if request.method == 'POST':
        if request.FILES.get('mainphoto'):
            new_article=Post.objects.create(
                postname=request.POST['postname'],
                contents=request.POST['contents'],
                mainphoto=request.FILES.get('mainphoto'),
            )
        else:
            new_article=Post.objects.create(
                postname=request.POST['postname'],
                contents=request.POST['contents'],
                mainphoto=request.POST.get('mainphoto'),
            )
        return redirect('/blog/')
    return render(request, 'main/new_post.html')


def remove_post(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('/blog/')
    return render(request, 'main/remove_post.html', {'Post': post})

def edit_post(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        post.postname = post.postname
        post.contents = request.POST.get('contents')
        post.mainphoto = request.FILES.get('mainphoto')
        post.save()
        return redirect('blog')
    return render(request, 'main/edit_post.html', {'Post': post})

main/templates/main/blog.html
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog list</title>
</head>
<body>
    <h1>게시판 페이지입니다</h1>
    <table>
        {% for list in postlist %}
            <ul>
                <li><a href="{{list.pk}}/">{{ list.postname }}</a></li>
            </ul>
        {% endfor %}
    </table>
    <button><a href="new_post/">글쓰기</a></button>
</body>
</html>

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>title</title>
</head>
<body>
    장고 첫 페이지!!
</body>
</html>

main/templates/main/posting.html
<html>
    <head>
        <title>Posting!</title>
    </head>
    <body>
        <h1>게시글 개별 페이지입니다</h1>
        <p>{{post.postname}}</p>
        <p>{{post.contents}}</p>
        {% if post.mainphoto %}
            <img src="{{ post.mainphoto.url }}" alt="" height="600">
            <br>
        {% endif %}
        <p><a href="/blog/">목록</a></p>
    </body>
</html>

templates/common/login.html
{% block content %}
<div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div>
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div>
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit">로그인</button>
        <div>
            계정이 없으신가요?<br>
            회원가입은 <a href="{% url 'common:signup' %}"> 여기 </a> 를 클릭하세요
        </div>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div>
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div>
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>title</title>
</head>
<body>
    <h3>SNS할바에 내가 만들고 말지</h3>
    <a href="{% url 'common:login' %}">Login</a>
</body>
</html>

templates/main/blog.html
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog list</title>
</head>
<body>
    {% if user.is_authenticated %}
    <h1>게시판 페이지입니다</h1>
    <table>
        {% for list in postlist %}
            <ul>
                <li><a href="{{list.pk}}/">{{ list.postname }}</a></li>
            </ul>
        {% endfor %}
    </table>
    <button><a href="new_post/">글쓰기</a></button>
    <button><a href="{% url 'common:logout' %}">로그아웃</a></button>
    {% else %}
    <button><a href="{% url 'common:login' %}">로그인</a></button>
    {% endif %}
</body>
</html>

templates/main/edit_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글 편집</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        내용<br>
        <textarea rows="10" cols="50" name="contents"></textarea><br>
        <input type="file" name="mainphoto"><br>
        <input type="submit" value="편집내용 저장">
    </form>
</body>
</html>

templates/main/new_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글쓰기 페이지</title>
</head>
<body>
    <h1>글쓰기 페이지</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        제목<br>
        <input type="text" name="postname"><br>
        내용<br>
        <textarea rows="10" cols="50" name="contents"></textarea><br>
        <input type="file" name="mainphoto"><br>
        <input type="submit" value="글쓰기">
    </form>
</body>
</html>

templates/main/posting.html
<html>
    <head>
        <title>Posting!</title>
    </head>
    <body>
        <h1>게시글 개별 페이지입니다</h1>
        <p>{{post.postname}}</p>
        <p>{{post.contents}}</p>
        {% if post.mainphoto %}
            <img src="{{ post.mainphoto.url }}" alt="" height="600">
            <br>
        {% endif %}
        <a href="/blog/{{post.pk}}/edit">편집</a>
        <a href="/blog/{{post.pk}}/remove">삭제</a>
        <p><a href="/blog/">목록</a></p>
    </body>
</html>

templates/main/remove_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글 삭제</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <h3>{{ Post.postname }} - 삭제하기</h3>
        <button>삭제</button>
    </form>
</body>
</html>